-- Deprecated: do not create customer_support_inquiry or inquiry_message.
-- The canonical customer inquiry/thread storage is the original contact table.
-- Apply ../sql/restore_legacy_commerce_schema.sql after reviewing its preflight and taking a backup.
